import type { HeadersFunction, LoaderFunctionArgs } from "react-router";
import { useLoaderData } from "react-router";
import { boundary } from "@shopify/shopify-app-react-router/server";
import { authenticate } from "../shopify.server";
import db from "../db.server";
import StatCard from "../components/dashboard/StatCard";
import QuickAction from "../components/dashboard/QuickAction";
import { getShopLanguage, getTranslations } from "../i18n.server";
import "../styles/launchpilot.css";
export const loader=async({request}:LoaderFunctionArgs)=>{const{admin,session}=await authenticate.admin(request);let shopName="your store",productCount=0;try{const r=await admin.graphql(`
    #graphql
    query Dashboard { shop { name } productsCount { count } }`);const j=await r.json();shopName=j.data?.shop?.name||shopName;productCount=j.data?.productsCount?.count||0;}catch{}const[campaignCount,scheduledCount,settings,autopilot,adsCount,language]=await Promise.all([db.campaign.count({where:{shop:session.shop}}),db.scheduledPost.count({where:{shop:session.shop,status:"scheduled"}}),db.brandSettings.findUnique({where:{shop:session.shop}}),db.autopilotConfig.findUnique({where:{shop:session.shop}}),db.adsCampaign.count({where:{shop:session.shop}}),getShopLanguage(session.shop)]);return{shopName,productCount,campaignCount,scheduledCount,configured:Boolean(settings),autopilot:Boolean(autopilot?.enabled),adsCount,language};};
export default function Dashboard(){const d=useLoaderData<typeof loader>();const t=getTranslations(d.language);return <s-page heading="LaunchPilot"><s-button slot="primary-action" variant="primary" href="/app/studio">{t("create_campaign")}</s-button><div className="lp-dashboard"><section className="lp-hero"><div className="lp-hero-copy"><p className="lp-kicker">{t("hero_kicker")}</p><h2>{t("hero_title")}</h2><p className="lp-hero-description">{t("hero_desc",{shop:d.shopName})}</p><div className="lp-hero-actions"><s-button variant="primary" href="/app/studio">{t("create_with_ai")}</s-button><s-button href="/app/settings">{t("configure_brand")}</s-button></div></div><div className="lp-hero-mark">🚀</div></section><section className="lp-stats-grid"><StatCard label={t("products")} value={String(d.productCount)} hint={t("synced_shopify")} icon="📦"/><StatCard label={t("campaigns")} value={String(d.campaignCount)} hint={t("saved_content")} icon="✨"/><StatCard label={t("scheduled")} value={String(d.scheduledCount)} hint={t("upcoming_posts")} icon="📅"/><StatCard label={t("setup")} value={d.configured?t("ready"):t("start")} hint={t("brand_workspace")} icon="⚙️"/></section><section className="lp-main-grid"><div className="lp-panel"><div className="lp-panel-header"><div><h3 className="lp-panel-title">{t("quick_actions")}</h3><p className="lp-panel-subtitle">{t("quick_desc")}</p></div></div><div className="lp-actions-list"><QuickAction title={t("products")} description={t("browse_catalog")} icon="🛍️" href="/app/products"/><QuickAction title={t("studio")} description={t("generate_copy_images")} icon="🎨" href="/app/studio" badge={t("core")}/><QuickAction title={t("calendar")} description={t("schedule_drafts")} icon="🗓️" href="/app/calendar"/><QuickAction title="Autopilot" description={t("autopilot_desc")} icon="🤖" href="/app/autopilot" badge={d.autopilot?t("on"):t("new")}/><QuickAction title={t("ads_manager")} description={t("ads_desc",{count:d.adsCount})} icon="📣" href="/app/ads"/><QuickAction title={t("analytics")} description={t("analytics_desc")} icon="📊" href="/app/analytics"/></div></div><aside className="lp-panel lp-autopilot"><div><div className="lp-autopilot-status"><span className="lp-status-dot"/>{t("mvp_ready")}</div><h3 className="lp-panel-title" style={{marginTop:14}}>{t("launch_checklist")}</h3><p className="lp-panel-subtitle">{t("core_connected")}</p></div><ul className="lp-checklist"><li><span className="lp-check">✓</span>{t("real_products")}</li><li><span className="lp-check">✓</span>{t("campaign_storage")}</li><li><span className="lp-check">✓</span>{t("downloadable_images")}</li><li><span className="lp-check">✓</span>{t("scheduling_brand")}</li><li><span className="lp-check">→</span>{t("meta_review")}</li></ul><div className="lp-hero-actions"><s-button href="/app/autopilot">{t("open_autopilot")}</s-button><s-button href="/app/billing">{t("plans")}</s-button></div></aside></section></div></s-page>}
export const headers:HeadersFunction=(args)=>boundary.headers(args);
